language: python
sudo: false
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "sh install_test_deps.sh"
    - "pip uninstall -y xblock-drag-and-drop-v2"
    - "python setup.py sdist"
    - "pip install dist/xblock-drag-and-drop-v2-2.0.7.tar.gz"
script:
    - pep8 drag_and_drop_v2 tests --max-line-length=120
    - pylint drag_and_drop_v2
    - pylint tests --rcfile=tests/pylintrc
    - python run_tests.py
notifications:
    email: false
addons:
    firefox: "43.0"
